//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BasvuruKayit.Veritabani
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Ogrenci
    {
        public int OgrenciID { get; set; }
        public int BireyID { get; set; }
        public string OgrenciNo { get; set; }
        public short BolumID { get; set; }
        public int BasvuruDurumID { get; set; }
        public string OgrenciFoto { get; set; }
        public byte Sinif { get; set; }
        public string Email { get; set; }
    
        public virtual tbl_BasvuruDurum tbl_BasvuruDurum { get; set; }
        public virtual tbl_Bolum tbl_Bolum { get; set; }
    }
}
