//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BasvuruKayit.Veritabani
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SinavTip
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_SinavTip()
        {
            this.tbl_Sinav = new HashSet<tbl_Sinav>();
        }
    
        public byte SinavTipID { get; set; }
        public string SinavTipAd { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Sinav> tbl_Sinav { get; set; }
    }
}
