//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BasvuruKayit.Veritabani
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PersonelDers
    {
        public int PersonelDersID { get; set; }
        public int PersonelID { get; set; }
        public int DersID { get; set; }
    
        public virtual tbl_Ders tbl_Ders { get; set; }
    }
}
